### ISSUE TITLE
search_source() Function Requires Missing language Parameter in Configuration

### ISSUE THREAD

**Issue by kalina2002** [google/oss-fuzz-gen#644]
https://github.com/google/oss-fuzz-gen/tree/main/data_prep
I have a question about project_src.py ： search_source() function requires five parameters, but the configuration in your configs list only contains four parameters. The missing parameter is language, which is required by the search_source() function but not passed in the configuration.
![bug](https://github.com/user-attachments/assets/d31188a9-5213-4ced-bb2a-a0b279cda9c4)

it seems the language parameter will receive args.result_dir as its value  .

**Comment by DavidKorczynski** [comment]
This is by and large because the `main` function use of `search_source` has been faced out. `search_source` is used for benchmark generation and this is primarily done by way of these args https://github.com/google/oss-fuzz-gen/blob/5fbf0a3c9c1e1d22c7be3e888d4633466f575115/run_all_experiments.py#L236-L253 or perhaps the logic from here: https://github.com/google/oss-fuzz-gen/blob/5fbf0a3c9c1e1d22c7be3e888d4633466f575115/data_prep/introspector.py#L1031 (although I personally always use the `run_all_experiments.py` to generate benchmarks.

We're also trying to face out the use of `search_source` as it adds a fair amount of overhead for generating benchmarks. The ideal situation is if we push this logic into introspector so we can generate it dynamically on a daily basis. I think the best is to delete the `main` calling into `search_source`.
